version: 0.2
env:
  parameter-store:
    db_user: 
    db_pwd:
    db_url: 

phases:
  install:
    runtime-versions:
      python 3.7

  pre_build:
    commands:
      - echo "Pull down flyway tool"
      - $ wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.8.1/flyway-commandline-7.8.1-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-7.8.1/flyway /usr/local/bin


  build:
    commands:
      - echo "Build something ... "

  post_build:
    commands:
      - echo "CURRENT MIGRATION STATUS"
      .fl

